import { fileURLToPath } from 'node:url'

import { defineConfig } from 'vitest/config'

export default defineConfig({
  // Unit tests never load developer credentials from .env or .env.local.
  envDir: false,
  resolve: { alias: { '@': fileURLToPath(new URL('.', import.meta.url)) } },
  test: {
    include: ['tests/**/*.test.ts'],
    setupFiles: ['tests/setup.ts'],
    // Override inherited shell/CI credentials before loading test modules.
    env: {
      OPENAI_API_KEY: '',
      STRIPE_SECRET_KEY: '',
      STRIPE_WEBHOOK_SECRET: '',
      STRIPE_UPGRADE_PORTAL_CONFIGURATION_ID: '',
      STRIPE_PLUS_MONTHLY_PRICE_ID: '',
      STRIPE_PLUS_ANNUAL_PRICE_ID: '',
      STRIPE_PRO_MONTHLY_PRICE_ID: '',
      STRIPE_PRO_ANNUAL_PRICE_ID: '',
      STRIPE_IMAGE_PACK_PRICE_ID: '',
      STRIPE_LIVE_CHECKOUT_ENABLED: '',
      R2_ACCOUNT_ID: '',
      R2_ACCESS_KEY_ID: '',
      R2_SECRET_ACCESS_KEY: '',
      R2_PUBLIC_BUCKET: '',
      R2_PRIVATE_BUCKET: '',
      R2_PUBLIC_URL: '',
      R2_ENDPOINT: '',
      S3_ACCESS_KEY_ID: '',
      S3_SECRET_ACCESS_KEY: '',
      S3_API_ENDPOINT: '',
      S3_BUCKET_NAME: '',
      S3_PRIVATE_BUCKET_NAME: '',
      S3_PUBLIC_URL: '',
      IMAGE_AI_MODEL: '',
      IMAGE_GENERATION_ENABLED: '',
      IMAGE_AI_MONTHLY_BUDGET_USD: '',
      IMAGE_GENERATION_CONCURRENCY: '',
      WORKFLOW_TARGET_WORLD: 'local',
      WORKFLOW_LOCAL_BASE_URL: '',
      WORKFLOW_LOCAL_DATA_DIR: '',
      RESEND_API_KEY: '',
      RESEND_FROM_EMAIL: '',
      RESEND_REPLY_TO: '',
      EMAIL_FROM: '',
      EMAIL_REPLY_TO: '',
      GOOGLE_CLIENT_ID: '',
      GOOGLE_CLIENT_SECRET: '',
      GITHUB_CLIENT_ID: '',
      GITHUB_CLIENT_SECRET: '',
      BETTER_AUTH_SECRET: '',
      BETTER_AUTH_URL: '',
      ANTHROPIC_API_KEY: '',
      AI_GATEWAY_API_KEY: '',
      VERCEL_OIDC_TOKEN: '',
      VERCEL: '',
      VERCEL_ENV: '',
      VERCEL_TARGET_ENV: '',
      VERCEL_PROJECT_PRODUCTION_URL: '',
      VERCEL_BRANCH_URL: '',
      VERCEL_URL: '',
      PORTLESS_URL: '',
      PORT: '3000'
    },
    testTimeout: 15_000,
    hookTimeout: 30_000
  }
})
